export const product_data = [
  {
    id: "1",
    name: "iPhone 13 Pro",
    brand: "Apple",
    price: 699,
    originalPrice: 999,
    rating: 4.8,
    reviews: 124,
    image: "/images/phone/i14promax.jpg",
    gallery_images: [
      "/images/phone/i14promax.jpg",
      "/images/phone/i14promax1.jpg",
      "/images/phone/i14promax2.jpg",
      "/images/phone/i14promax3.jpg",
      "/images/phone/i14promax4.jpg",
    ],
    condition: "Excellent",
    storage: "128GB",
    color: "Graphite",
    category: "iPhone",
    availability: "in-stock",
    description:
      "The iPhone 13 Pro delivers exceptional performance with the A15 Bionic chip, ProRAW photography capabilities, and a stunning Super Retina XDR display with ProMotion technology.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Super Retina XDR OLED",
        resolution: "2532 x 1170 pixels",
        features: ["ProMotion 120Hz", "HDR10", "Dolby Vision"],
      },
      performance: {
        processor: "A15 Bionic chip",
        ram: "6GB",
        storage: "128GB",
        os: "iOS 15 (upgradable)",
      },
      camera: {
        rear: "Triple 12MP (Main, Ultra Wide, Telephoto)",
        front: "12MP TrueDepth",
        features: ["ProRAW", "ProRes video", "Cinematic mode", "Night mode"],
      },
      battery: {
        capacity: "3095 mAh",
        charging: "20W wired, 15W MagSafe wireless",
        life: "Up to 22 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.0",
        other: ["Lightning port", "Face ID", "MagSafe"],
      },
      physical: {
        dimensions: "146.7 x 71.5 x 7.65 mm",
        weight: "203g",
        materials: "Stainless steel frame, Ceramic Shield front",
        colors: ["Graphite", "Gold", "Silver", "Sierra Blue", "Alpine Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 15,
    features: [
      "ProMotion 120Hz display",
      "A15 Bionic chip",
      "Pro camera system",
      "5G connectivity",
      "Face ID",
      "MagSafe compatible",
    ],
  },
  {
    id: "2",
    name: "Galaxy S22 Ultra",
    brand: "Samsung",
    price: 599,
    originalPrice: 899,
    rating: 4.7,
    reviews: 89,
    image: "/placeholder.svg?height=600&width=600",
    gallery_images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    condition: "Very Good",
    storage: "256GB",
    color: "Phantom Black",
    category: "Samsung",
    availability: "in-stock",
    description:
      "The Galaxy S22 Ultra combines the best of Galaxy Note and Galaxy S series, featuring the built-in S Pen, advanced camera system, and powerful performance.",
    specifications: {
      display: {
        size: "6.8 inches",
        type: "Dynamic AMOLED 2X",
        resolution: "3088 x 1440 pixels",
        features: [
          "120Hz adaptive refresh rate",
          "HDR10+",
          "Always-on display",
        ],
      },
      performance: {
        processor: "Snapdragon 8 Gen 1",
        ram: "8GB",
        storage: "256GB",
        os: "Android 12 (One UI 4.1)",
      },
      camera: {
        rear: "Quad camera: 108MP main, 12MP ultra-wide, 10MP telephoto (3x), 10MP periscope (10x)",
        front: "40MP",
        features: [
          "100x Space Zoom",
          "8K video recording",
          "Night mode",
          "Pro mode",
        ],
      },
      battery: {
        capacity: "5000 mAh",
        charging: "45W wired, 15W wireless, 4.5W reverse wireless",
        life: "Up to 26 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Fingerprint (ultrasonic)", "S Pen"],
      },
      physical: {
        dimensions: "163.3 x 77.9 x 8.9 mm",
        weight: "228g",
        materials: "Aluminum frame, Gorilla Glass Victus+",
        colors: ["Phantom Black", "Phantom White", "Burgundy", "Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 8,
    features: [
      "Built-in S Pen",
      "108MP camera",
      "100x Space Zoom",
      "5000mAh battery",
      "120Hz display",
      "5G ready",
    ],
  },
  {
    id: "3",
    name: "Pixel 7 Pro",
    brand: "Pixel",
    price: 620.77,
    originalPrice: 835.57,
    rating: 4.8,
    reviews: 147,
    image: "/images/phone/i14promax.jpg",
    gallery_images: [
      "/images/phone/i14promax.jpg",
      "/images/phone/i14promax1.jpg",
      "/images/phone/i14promax2.jpg",
      "/images/phone/i14promax3.jpg",
      "/images/phone/i14promax4.jpg",
    ],
    condition: "Excellent",
    storage: "128GB",
    color: "Snow",
    category: "Pixel",
    availability: "in-stock",
    description:
      "Pixel 7 Pro offers Google's best camera system with Tensor G2 chip and clean Android experience.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Super Retina XDR OLED",
        resolution: "2532 x 1170 pixels",
        features: ["ProMotion 120Hz", "HDR10", "Dolby Vision"],
      },
      performance: {
        processor: "Google Tensor G2",
        ram: "8GB",
        storage: "128GB",
        os: "Android 13",
      },
      camera: {
        rear: "Triple camera: 50MP wide, 48MP telephoto, 12MP ultrawide",
        front: "10.8MP",
        features: ["Super Res Zoom", "Night Sight", "Magic Eraser"],
      },
      battery: {
        capacity: "3095 mAh",
        charging: "20W wired, 15W MagSafe wireless",
        life: "Up to 22 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Face Unlock", "In-display Fingerprint"],
      },
      physical: {
        dimensions: "162.9 x 76.6 x 8.9 mm",
        weight: "212g",
        materials: "Polished aluminum frame, Gorilla Glass Victus",
        colors: ["Obsidian", "Snow", "Hazel"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 13,
    features: [
      "Tensor G2 chip",
      "Triple rear camera",
      "Smooth Display 120Hz",
      "5G connectivity",
    ],
  },
  {
    id: "4",
    name: "OnePlus 10",
    brand: "OnePlus",
    price: 399,
    originalPrice: 599,
    rating: 4.5,
    reviews: 45,
    image: "/images/phone/i14promax.jpg",
    gallery_images: [
      "/images/phone/i14promax.jpg",
      "/images/phone/i14promax1.jpg",
      "/images/phone/i14promax2.jpg",
      "/images/phone/i14promax3.jpg",
      "/images/phone/i14promax4.jpg",
    ],
    condition: "Good",
    storage: "256GB",
    color: "Volcanic Black",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus 11 delivers top-tier performance with Snapdragon 8 Gen 2, 120Hz AMOLED, and fast charging.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Super Retina XDR OLED",
        resolution: "2532 x 1170 pixels",
        features: ["ProMotion 120Hz", "HDR10", "Dolby Vision"],
      },
      performance: {
        processor: "Snapdragon 8 Gen 2",
        ram: "12GB",
        storage: "256GB",
        os: "Android 13 (OxygenOS)",
      },
      camera: {
        rear: "Triple camera: 50MP main, 48MP ultra-wide, 32MP telephoto",
        front: "16MP",
        features: ["Hasselblad tuning", "Nightscape", "4K 60fps video"],
      },
      battery: {
        capacity: "3095 mAh",
        charging: "20W wired, 15W MagSafe wireless",
        life: "Up to 22 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.3",
        other: ["USB-C", "In-display Fingerprint", "Alert Slider"],
      },
      physical: {
        dimensions: "163.1 x 74.1 x 8.5 mm",
        weight: "205g",
        materials: "Aluminum frame, Gorilla Glass 5",
        colors: ["Titan Black", "Eternal Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 12,
    features: [
      "Snapdragon 8 Gen 2",
      "120Hz AMOLED",
      "100W fast charging",
      "Hasselblad camera",
    ],
  },
  {
    id: "5",
    name: "Galaxy S22 Ultra",
    brand: "Samsung",
    price: 593.06,
    originalPrice: 855.7,
    rating: 4.4,
    reviews: 161,
    image: "/images/phone/i14promax.jpg",
    gallery_images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    condition: "Very Good",
    storage: "256GB",
    color: "Phantom Black",
    category: "Samsung",
    availability: "in-stock",
    description:
      "The Galaxy S22 Ultra combines the best of Galaxy Note and Galaxy S series...",
    specifications: {
      display: {
        size: "6.8 inches",
        type: "Dynamic AMOLED 2X",
        resolution: "3088 x 1440 pixels",
        features: [
          "120Hz adaptive refresh rate",
          "HDR10+",
          "Always-on display",
        ],
      },
      performance: {
        processor: "Snapdragon 8 Gen 1",
        ram: "8GB",
        storage: "256GB",
        os: "Android 12 (One UI 4.1)",
      },
      camera: {
        rear: "Quad camera: 108MP main, 12MP ultra-wide, 10MP telephoto (3x), 10MP periscope (10x)",
        front: "40MP",
        features: [
          "100x Space Zoom",
          "8K video recording",
          "Night mode",
          "Pro mode",
        ],
      },
      battery: {
        capacity: "5000 mAh",
        charging: "45W wired, 15W wireless, 4.5W reverse wireless",
        life: "Up to 26 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Fingerprint (ultrasonic)", "S Pen"],
      },
      physical: {
        dimensions: "163.3 x 77.9 x 8.9 mm",
        weight: "228g",
        materials: "Aluminum frame, Gorilla Glass Victus+",
        colors: ["Phantom Black", "Phantom White", "Burgundy", "Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 20,
    features: [
      "Built-in S Pen",
      "108MP camera",
      "100x Space Zoom",
      "5000mAh battery",
      "120Hz display",
      "5G ready",
    ],
  },
  {
    id: "6",
    name: "OnePlus 11",
    brand: "OnePlus",
    price: 606.2,
    originalPrice: 847.23,
    rating: 4.7,
    reviews: 190,
    image: "/images/phone/i14promax.jpg",
    gallery_images: [
      "/images/phone/i14promax.jpg",
      "/images/phone/i14promax1.jpg",
      "/images/phone/i14promax2.jpg",
      "/images/phone/i14promax3.jpg",
      "/images/phone/i14promax4.jpg",
    ],
    condition: "Excellent",
    storage: "128GB",
    color: "Eternal Green",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus 11 delivers top-tier performance with Snapdragon 8 Gen 2, 120Hz AMOLED, and fast charging.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Super Retina XDR OLED",
        resolution: "2532 x 1170 pixels",
        features: ["ProMotion 120Hz", "HDR10", "Dolby Vision"],
      },
      performance: {
        processor: "Snapdragon 8 Gen 2",
        ram: "12GB",
        storage: "256GB",
        os: "Android 13 (OxygenOS)",
      },
      camera: {
        rear: "Triple camera: 50MP main, 48MP ultra-wide, 32MP telephoto",
        front: "16MP",
        features: ["Hasselblad tuning", "Nightscape", "4K 60fps video"],
      },
      battery: {
        capacity: "3095 mAh",
        charging: "20W wired, 15W MagSafe wireless",
        life: "Up to 22 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.3",
        other: ["USB-C", "In-display Fingerprint", "Alert Slider"],
      },
      physical: {
        dimensions: "163.1 x 74.1 x 8.5 mm",
        weight: "205g",
        materials: "Aluminum frame, Gorilla Glass 5",
        colors: ["Titan Black", "Eternal Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 14,
    features: [
      "Snapdragon 8 Gen 2",
      "120Hz AMOLED",
      "100W fast charging",
      "Hasselblad camera",
    ],
  },
  {
    id: "7",
    name: "OnePlus 11",
    brand: "OnePlus",
    price: 542.95,
    originalPrice: 856.68,
    rating: 4.9,
    reviews: 103,
    image: "/images/phone/i14promax.jpg",
    gallery_images: [
      "/images/phone/i14promax.jpg",
      "/images/phone/i14promax1.jpg",
      "/images/phone/i14promax2.jpg",
      "/images/phone/i14promax3.jpg",
      "/images/phone/i14promax4.jpg",
    ],
    condition: "Excellent",
    storage: "128GB",
    color: "Titan Black",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus 11 delivers top-tier performance with Snapdragon 8 Gen 2, 120Hz AMOLED, and fast charging.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Super Retina XDR OLED",
        resolution: "2532 x 1170 pixels",
        features: ["ProMotion 120Hz", "HDR10", "Dolby Vision"],
      },
      performance: {
        processor: "Snapdragon 8 Gen 2",
        ram: "12GB",
        storage: "256GB",
        os: "Android 13 (OxygenOS)",
      },
      camera: {
        rear: "Triple camera: 50MP main, 48MP ultra-wide, 32MP telephoto",
        front: "16MP",
        features: ["Hasselblad tuning", "Nightscape", "4K 60fps video"],
      },
      battery: {
        capacity: "3095 mAh",
        charging: "20W wired, 15W MagSafe wireless",
        life: "Up to 22 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.3",
        other: ["USB-C", "In-display Fingerprint", "Alert Slider"],
      },
      physical: {
        dimensions: "163.1 x 74.1 x 8.5 mm",
        weight: "205g",
        materials: "Aluminum frame, Gorilla Glass 5",
        colors: ["Titan Black", "Eternal Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 12,
    features: [
      "Snapdragon 8 Gen 2",
      "120Hz AMOLED",
      "100W fast charging",
      "Hasselblad camera",
    ],
  },
  {
    id: "8",
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    price: 1099,
    originalPrice: 1299,
    rating: 4.9,
    reviews: 215,
    image: "/images/phone/iphone14promax.jpg",
    gallery_images: [
      "/images/phone/iphone14promax.jpg",
      "/images/phone/iphone14promax1.jpg",
      "/images/phone/iphone14promax2.jpg",
      "/images/phone/iphone14promax3.jpg",
    ],
    condition: "Excellent",
    storage: "256GB",
    color: "Deep Purple",
    category: "iPhone",
    availability: "in-stock",
    description:
      "iPhone 14 Pro Max features the Dynamic Island, Always-On display, pro camera system, and A16 Bionic chip for unprecedented performance.",
    specifications: {
      display: {
        size: "6.7 inches",
        type: "Super Retina XDR OLED",
        resolution: "2796 x 1290 pixels",
        features: [
          "ProMotion 120Hz",
          "Always-On display",
          "HDR10",
          "Dolby Vision",
        ],
      },
      performance: {
        processor: "A16 Bionic chip",
        ram: "6GB",
        storage: "256GB",
        os: "iOS 16",
      },
      camera: {
        rear: "Triple 48MP Main, 12MP Ultra Wide, 12MP Telephoto",
        front: "12MP TrueDepth",
        features: [
          "ProRAW",
          "Cinematic mode (4K HDR)",
          "Photonic Engine",
          "Night mode",
        ],
      },
      battery: {
        capacity: "4323 mAh",
        charging: "27W wired, 15W MagSafe wireless",
        life: "Up to 29 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.3",
        other: ["Lightning port", "Face ID", "Emergency SOS via satellite"],
      },
      physical: {
        dimensions: "160.7 x 77.6 x 7.85 mm",
        weight: "240g",
        materials: "Surgical-grade stainless steel, Ceramic Shield front",
        colors: ["Deep Purple", "Gold", "Silver", "Space Black"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 18,
    features: [
      "Dynamic Island",
      "A16 Bionic chip",
      "48MP Main camera",
      "Always-On display",
      "Emergency SOS",
      "5G connectivity",
    ],
  },
  {
    id: "9",
    name: "Galaxy Z Fold 4",
    brand: "Samsung",
    price: 1599,
    originalPrice: 1799,
    rating: 4.6,
    reviews: 78,
    image: "/images/phone/zfold4.jpg",
    gallery_images: [
      "/images/phone/zfold4.jpg",
      "/images/phone/zfold41.jpg",
      "/images/phone/zfold42.jpg",
      "/images/phone/zfold43.jpg",
    ],
    condition: "Excellent",
    storage: "512GB",
    color: "Graygreen",
    category: "Samsung",
    availability: "in-stock",
    description:
      "Galaxy Z Fold 4 is Samsung's most advanced foldable phone with improved Flex Mode, S Pen support, and powerful Snapdragon 8+ Gen 1 processor.",
    specifications: {
      display: {
        main: "7.6 inches Dynamic AMOLED 2X",
        cover: "6.2 inches Dynamic AMOLED 2X",
        resolution: "Main: 2176 x 1812, Cover: 2316 x 904",
        features: ["120Hz adaptive refresh rate", "UTG", "HDR10+"],
      },
      performance: {
        processor: "Snapdragon 8+ Gen 1",
        ram: "12GB",
        storage: "512GB",
        os: "Android 12L (One UI 4.1.1)",
      },
      camera: {
        rear: "Triple 50MP wide, 12MP ultrawide, 10MP telephoto",
        cover: "10MP",
        "under-display": "4MP",
        features: ["30x Space Zoom", "Director's View", "Nightography"],
      },
      battery: {
        capacity: "4400 mAh",
        charging: "25W wired, 15W wireless, 4.5W reverse wireless",
        life: "Up to 20 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Side-mounted fingerprint", "S Pen support"],
      },
      physical: {
        dimensions:
          "Unfolded: 155.1 x 130.1 x 6.3 mm, Folded: 155.1 x 67.1 x 14.2-15.8 mm",
        weight: "263g",
        materials: "Armor Aluminum frame, Gorilla Glass Victus+",
        colors: ["Graygreen", "Phantom Black", "Beige"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 7,
    features: [
      "Foldable Dynamic AMOLED 2X",
      "S Pen support",
      "Multi-active window",
      "Under-display camera",
      "IPX8 water resistance",
      "5G ready",
    ],
  },
  {
    id: "10",
    name: "Pixel 6a",
    brand: "Pixel",
    price: 349,
    originalPrice: 449,
    rating: 4.5,
    reviews: 92,
    image: "/images/phone/pixel6a.jpg",
    gallery_images: [
      "/images/phone/pixel6a.jpg",
      "/images/phone/pixel6a1.jpg",
      "/images/phone/pixel6a2.jpg",
      "/images/phone/pixel6a3.jpg",
    ],
    condition: "Good",
    storage: "128GB",
    color: "Chalk",
    category: "Pixel",
    availability: "in-stock",
    description:
      "Pixel 6a delivers the essential Pixel experience with Google Tensor chip, great camera, and pure Android at an affordable price.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "OLED",
        resolution: "2400 x 1080 pixels",
        features: ["60Hz refresh rate", "HDR", "Always-on display"],
      },
      performance: {
        processor: "Google Tensor",
        ram: "6GB",
        storage: "128GB",
        os: "Android 12",
      },
      camera: {
        rear: "Dual 12.2MP main, 12MP ultrawide",
        front: "8MP",
        features: ["Night Sight", "Real Tone", "Magic Eraser", "Portrait Mode"],
      },
      battery: {
        capacity: "4410 mAh",
        charging: "18W wired",
        life: "Up to 24 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Titan M2 security", "In-display fingerprint"],
      },
      physical: {
        dimensions: "152.2 x 71.8 x 8.9 mm",
        weight: "178g",
        materials: "Polycarbonate unibody, Gorilla Glass 3",
        colors: ["Chalk", "Charcoal", "Sage"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 22,
    features: [
      "Google Tensor chip",
      "Titan M2 security",
      "Magic Eraser",
      "Real Tone",
      "5G ready",
      "Pure Android",
    ],
  },
  {
    id: "11",
    name: "OnePlus Nord 2T",
    brand: "OnePlus",
    price: 399,
    originalPrice: 499,
    rating: 4.3,
    reviews: 67,
    image: "/images/phone/nord2t.jpg",
    gallery_images: [
      "/images/phone/nord2t.jpg",
      "/images/phone/nord2t1.jpg",
      "/images/phone/nord2t2.jpg",
      "/images/phone/nord2t3.jpg",
    ],
    condition: "Good",
    storage: "128GB",
    color: "Jade Fog",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus Nord 2T offers flagship-level performance with MediaTek Dimensity 1300, 80W SuperVOOC charging, and OxygenOS experience.",
    specifications: {
      display: {
        size: "6.43 inches",
        type: "Fluid AMOLED",
        resolution: "2400 x 1080 pixels",
        features: ["90Hz refresh rate", "HDR10+", "sRGB"],
      },
      performance: {
        processor: "MediaTek Dimensity 1300",
        ram: "8GB",
        storage: "128GB",
        os: "Android 12 (OxygenOS 12.1)",
      },
      camera: {
        rear: "Triple 50MP main, 8MP ultrawide, 2MP mono",
        front: "32MP",
        features: ["Nightscape", "AI Photo Enhancement", "Portrait Mode"],
      },
      battery: {
        capacity: "4500 mAh",
        charging: "80W SuperVOOC",
        life: "Up to 30 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "In-display fingerprint", "Alert Slider"],
      },
      physical: {
        dimensions: "159.1 x 73.2 x 8.2 mm",
        weight: "190g",
        materials: "Plastic frame, Glass back",
        colors: ["Jade Fog", "Gray Shadow"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 15,
    features: [
      "Dimensity 1300",
      "80W SuperVOOC",
      "90Hz AMOLED",
      "OxygenOS",
      "5G ready",
      "Alert Slider",
    ],
  },
  {
    id: "12",
    name: "iPhone SE (3rd Gen)",
    brand: "Apple",
    price: 429,
    originalPrice: 529,
    rating: 4.2,
    reviews: 84,
    image: "/images/phone/iphonese3.jpg",
    gallery_images: [
      "/images/phone/iphonese3.jpg",
      "/images/phone/iphonese31.jpg",
      "/images/phone/iphonese32.jpg",
      "/images/phone/iphonese33.jpg",
    ],
    condition: "Good",
    storage: "64GB",
    color: "Midnight",
    category: "iPhone",
    availability: "in-stock",
    description:
      "iPhone SE packs the powerful A15 Bionic chip into a classic design with Touch ID, great camera, and 5G connectivity.",
    specifications: {
      display: {
        size: "4.7 inches",
        type: "Retina HD LCD",
        resolution: "1334 x 750 pixels",
        features: ["True Tone", "Wide color", "625 nits"],
      },
      performance: {
        processor: "A15 Bionic chip",
        ram: "4GB",
        storage: "64GB",
        os: "iOS 15",
      },
      camera: {
        rear: "Single 12MP",
        front: "7MP",
        features: [
          "Smart HDR 4",
          "Photographic Styles",
          "Deep Fusion",
          "Portrait mode",
        ],
      },
      battery: {
        capacity: "2018 mAh",
        charging: "20W wired, Qi wireless",
        life: "Up to 15 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.0",
        other: ["Lightning port", "Touch ID", "IP67 water resistance"],
      },
      physical: {
        dimensions: "138.4 x 67.3 x 7.3 mm",
        weight: "144g",
        materials: "Aerospace-grade aluminum, Glass",
        colors: ["Midnight", "Starlight", "Red"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 25,
    features: [
      "A15 Bionic chip",
      "5G connectivity",
      "Touch ID",
      "Single-camera system",
      "Compact design",
      "Wireless charging",
    ],
  },
  {
    id: "13",
    name: "Galaxy A53 5G",
    brand: "Samsung",
    price: 449,
    originalPrice: 499,
    rating: 4.1,
    reviews: 56,
    image: "/images/phone/a535g.jpg",
    gallery_images: [
      "/images/phone/a535g.jpg",
      "/images/phone/a535g1.jpg",
      "/images/phone/a535g2.jpg",
      "/images/phone/a535g3.jpg",
    ],
    condition: "Good",
    storage: "128GB",
    color: "Awesome Blue",
    category: "Samsung",
    availability: "in-stock",
    description:
      "Galaxy A53 5G offers great value with 120Hz AMOLED display, quad camera system, and long battery life with IP67 water resistance.",
    specifications: {
      display: {
        size: "6.5 inches",
        type: "Super AMOLED",
        resolution: "2400 x 1080 pixels",
        features: ["120Hz refresh rate", "800 nits", "Always-on display"],
      },
      performance: {
        processor: "Exynos 1280",
        ram: "6GB",
        storage: "128GB (expandable)",
        os: "Android 12 (One UI 4.1)",
      },
      camera: {
        rear: "Quad 64MP main, 12MP ultrawide, 5MP macro, 5MP depth",
        front: "32MP",
        features: ["OIS", "Night mode", "Super Steady video"],
      },
      battery: {
        capacity: "5000 mAh",
        charging: "25W wired",
        life: "Up to 32 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 5",
        bluetooth: "Bluetooth 5.1",
        other: ["USB-C", "Under-display fingerprint", "IP67 water resistance"],
      },
      physical: {
        dimensions: "159.6 x 74.8 x 8.1 mm",
        weight: "189g",
        materials: "Plastic frame, Glass front",
        colors: [
          "Awesome Blue",
          "Awesome Black",
          "Awesome White",
          "Awesome Peach",
        ],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 17,
    features: [
      "120Hz AMOLED",
      "Quad camera",
      "IP67 rating",
      "5000mAh battery",
      "5G ready",
      "Expandable storage",
    ],
  },
  {
    id: "14",
    name: "Pixel 6 Pro",
    brand: "Pixel",
    price: 699,
    originalPrice: 899,
    rating: 4.6,
    reviews: 134,
    image: "/images/phone/pixel6pro.jpg",
    gallery_images: [
      "/images/phone/pixel6pro.jpg",
      "/images/phone/pixel6pro1.jpg",
      "/images/phone/pixel6pro2.jpg",
      "/images/phone/pixel6pro3.jpg",
    ],
    condition: "Very Good",
    storage: "128GB",
    color: "Stormy Black",
    category: "Pixel",
    availability: "in-stock",
    description:
      "Pixel 6 Pro features Google Tensor chip, pro camera system with 4x optical zoom, and smooth 120Hz LTPO display.",
    specifications: {
      display: {
        size: "6.7 inches",
        type: "LTPO AMOLED",
        resolution: "3120 x 1440 pixels",
        features: ["120Hz adaptive refresh", "HDR10+", "Always-on display"],
      },
      performance: {
        processor: "Google Tensor",
        ram: "12GB",
        storage: "128GB",
        os: "Android 12",
      },
      camera: {
        rear: "Triple 50MP wide, 48MP telephoto, 12MP ultrawide",
        front: "11.1MP",
        features: [
          "4x optical zoom",
          "Magic Eraser",
          "Real Tone",
          "Face Unblur",
        ],
      },
      battery: {
        capacity: "5003 mAh",
        charging: "30W wired, 23W wireless",
        life: "Up to 28 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Titan M2 security", "In-display fingerprint"],
      },
      physical: {
        dimensions: "163.9 x 75.9 x 8.9 mm",
        weight: "210g",
        materials: "Aluminum frame, Gorilla Glass Victus",
        colors: ["Stormy Black", "Cloudy White", "Sorta Sunny"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 9,
    features: [
      "Google Tensor",
      "120Hz LTPO",
      "4x optical zoom",
      "Magic Eraser",
      "Titan M2 security",
      "5G ready",
    ],
  },
  {
    id: "15",
    name: "OnePlus 10T",
    brand: "OnePlus",
    price: 649,
    originalPrice: 749,
    rating: 4.4,
    reviews: 87,
    image: "/images/phone/10t.jpg",
    gallery_images: [
      "/images/phone/10t.jpg",
      "/images/phone/10t1.jpg",
      "/images/phone/10t2.jpg",
      "/images/phone/10t3.jpg",
    ],
    condition: "Excellent",
    storage: "256GB",
    color: "Moonstone Black",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus 10T is the performance flagship with Snapdragon 8+ Gen 1, 150W SUPERVOOC charging, and 120Hz Fluid AMOLED display.",
    specifications: {
      display: {
        size: "6.7 inches",
        type: "Fluid AMOLED",
        resolution: "2412 x 1080 pixels",
        features: ["120Hz refresh", "HDR10+", "sRGB", "1000Hz touch sampling"],
      },
      performance: {
        processor: "Snapdragon 8+ Gen 1",
        ram: "16GB",
        storage: "256GB",
        os: "Android 12 (OxygenOS 12.1)",
      },
      camera: {
        rear: "Triple 50MP main, 8MP ultrawide, 2MP macro",
        front: "16MP",
        features: ["Nightscape", "AI Highlight Video", "Portrait Mode"],
      },
      battery: {
        capacity: "4800 mAh",
        charging: "150W SUPERVOOC",
        life: "Up to 26 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.3",
        other: ["USB-C", "In-display fingerprint", "NFC"],
      },
      physical: {
        dimensions: "163 x 75.4 x 8.8 mm",
        weight: "203g",
        materials: "Polycarbonate frame, Glass back",
        colors: ["Moonstone Black", "Jade Green"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 11,
    features: [
      "Snapdragon 8+ Gen 1",
      "150W charging",
      "120Hz AMOLED",
      "16GB RAM",
      "OxygenOS",
      "5G ready",
    ],
  },
  {
    id: "16",
    name: "iPhone 12",
    brand: "Apple",
    price: 599,
    originalPrice: 799,
    rating: 4.5,
    reviews: 156,
    image: "/images/phone/iphone12.jpg",
    gallery_images: [
      "/images/phone/iphone12.jpg",
      "/images/phone/iphone121.jpg",
      "/images/phone/iphone122.jpg",
      "/images/phone/iphone123.jpg",
    ],
    condition: "Very Good",
    storage: "64GB",
    color: "Blue",
    category: "iPhone",
    availability: "in-stock",
    description:
      "iPhone 12 features a stunning Super Retina XDR display, A14 Bionic chip, dual-camera system, and Ceramic Shield front cover.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Super Retina XDR OLED",
        resolution: "2532 x 1170 pixels",
        features: ["HDR", "True Tone", "Wide color", "Ceramic Shield"],
      },
      performance: {
        processor: "A14 Bionic chip",
        ram: "4GB",
        storage: "64GB",
        os: "iOS 14 (upgradable)",
      },
      camera: {
        rear: "Dual 12MP (Wide, Ultra Wide)",
        front: "12MP TrueDepth",
        features: [
          "Night mode",
          "Deep Fusion",
          "Smart HDR 3",
          "Dolby Vision HDR",
        ],
      },
      battery: {
        capacity: "2815 mAh",
        charging: "20W wired, 15W MagSafe wireless",
        life: "Up to 17 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.0",
        other: ["Lightning port", "Face ID", "MagSafe"],
      },
      physical: {
        dimensions: "146.7 x 71.5 x 7.4 mm",
        weight: "164g",
        materials: "Aluminum frame, Glass back",
        colors: ["Black", "White", "Red", "Green", "Blue", "Purple"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 14,
    features: [
      "A14 Bionic chip",
      "Super Retina XDR",
      "Ceramic Shield",
      "5G connectivity",
      "MagSafe",
      "Dual-camera system",
    ],
  },
  {
    id: "17",
    name: "Galaxy S21 FE",
    brand: "Samsung",
    price: 499,
    originalPrice: 699,
    rating: 4.3,
    reviews: 72,
    image: "/images/phone/s21fe.jpg",
    gallery_images: [
      "/images/phone/s21fe.jpg",
      "/images/phone/s21fe1.jpg",
      "/images/phone/s21fe2.jpg",
      "/images/phone/s21fe3.jpg",
    ],
    condition: "Very Good",
    storage: "128GB",
    color: "Olive",
    category: "Samsung",
    availability: "in-stock",
    description:
      "Galaxy S21 FE delivers flagship features including 120Hz AMOLED, triple camera system, and powerful processor in a fan-favorite design.",
    specifications: {
      display: {
        size: "6.4 inches",
        type: "Dynamic AMOLED 2X",
        resolution: "2340 x 1080 pixels",
        features: ["120Hz adaptive refresh", "HDR10+", "Always-on display"],
      },
      performance: {
        processor: "Snapdragon 888/Exynos 2100",
        ram: "6GB",
        storage: "128GB",
        os: "Android 12 (One UI 4)",
      },
      camera: {
        rear: "Triple 12MP main, 12MP ultrawide, 8MP telephoto",
        front: "32MP",
        features: [
          "30x Space Zoom",
          "Single Take",
          "Night mode",
          "Director's View",
        ],
      },
      battery: {
        capacity: "4500 mAh",
        charging: "25W wired, 15W wireless, 4.5W reverse wireless",
        life: "Up to 24 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.0",
        other: ["USB-C", "Under-display fingerprint", "IP68 water resistance"],
      },
      physical: {
        dimensions: "155.7 x 74.5 x 7.9 mm",
        weight: "177g",
        materials: "Plastic back, Aluminum frame",
        colors: ["Olive", "Lavender", "White", "Graphite"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 10,
    features: [
      "120Hz AMOLED",
      "Triple camera",
      "IP68 rating",
      "4500mAh battery",
      "5G ready",
      "Flagship processor",
    ],
  },
  {
    id: "18",
    name: "Pixel 5a",
    brand: "Pixel",
    price: 449,
    originalPrice: 499,
    rating: 4.4,
    reviews: 63,
    image: "/images/phone/pixel5a.jpg",
    gallery_images: [
      "/images/phone/pixel5a.jpg",
      "/images/phone/pixel5a1.jpg",
      "/images/phone/pixel5a2.jpg",
      "/images/phone/pixel5a3.jpg",
    ],
    condition: "Good",
    storage: "128GB",
    color: "Mostly Black",
    category: "Pixel",
    availability: "in-stock",
    description:
      "Pixel 5a offers the best of Google in an affordable package with great camera, long battery life, and pure Android experience.",
    specifications: {
      display: {
        size: "6.34 inches",
        type: "OLED",
        resolution: "2400 x 1080 pixels",
        features: ["60Hz refresh", "HDR", "Always-on display"],
      },
      performance: {
        processor: "Snapdragon 765G",
        ram: "6GB",
        storage: "128GB",
        os: "Android 11 (upgradable)",
      },
      camera: {
        rear: "Dual 12.2MP main, 16MP ultrawide",
        front: "8MP",
        features: ["Night Sight", "Portrait Mode", "4K video"],
      },
      battery: {
        capacity: "4680 mAh",
        charging: "18W wired",
        life: "Up to 48 hours battery life",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 5",
        bluetooth: "Bluetooth 5.0",
        other: ["USB-C", "Rear fingerprint", "IP67 water resistance"],
      },
      physical: {
        dimensions: "154.9 x 73.7 x 7.6 mm",
        weight: "183g",
        materials: "Polycarbonate unibody",
        colors: ["Mostly Black"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 16,
    features: [
      "Great camera quality",
      "Long battery life",
      "Pure Android",
      "IP67 rating",
      "5G ready",
      "Affordable price",
    ],
  },
  {
    id: "19",
    name: "OnePlus 9 Pro",
    brand: "OnePlus",
    price: 699,
    originalPrice: 969,
    rating: 4.6,
    reviews: 98,
    image: "/images/phone/9pro.jpg",
    gallery_images: [
      "/images/phone/9pro.jpg",
      "/images/phone/9pro1.jpg",
      "/images/phone/9pro2.jpg",
      "/images/phone/9pro3.jpg",
    ],
    condition: "Excellent",
    storage: "256GB",
    color: "Morning Mist",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus 9 Pro features Hasselblad camera system, 120Hz LTPO display, Warp Charge 65T, and flagship Snapdragon 888 performance.",
    specifications: {
      display: {
        size: "6.7 inches",
        type: "Fluid AMOLED LTPO",
        resolution: "3216 x 1440 pixels",
        features: ["120Hz adaptive refresh", "HDR10+", "1300 nits peak"],
      },
      performance: {
        processor: "Snapdragon 888",
        ram: "12GB",
        storage: "256GB",
        os: "Android 11 (OxygenOS 11)",
      },
      camera: {
        rear: "Quad 48MP main, 50MP ultrawide, 8MP telephoto, 2MP mono",
        front: "16MP",
        features: ["Hasselblad color calibration", "Nightscape", "12-bit RAW"],
      },
      battery: {
        capacity: "4500 mAh",
        charging: "65W wired, 50W wireless",
        life: "Up to 28 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "In-display fingerprint", "Alert Slider", "IP68"],
      },
      physical: {
        dimensions: "163.2 x 73.6 x 8.7 mm",
        weight: "197g",
        materials: "Aluminum frame, Gorilla Glass",
        colors: ["Morning Mist", "Pine Green", "Stellar Black"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 8,
    features: [
      "Hasselblad camera",
      "120Hz LTPO",
      "65W charging",
      "IP68 rating",
      "Alert Slider",
      "5G ready",
    ],
  },
  {
    id: "20",
    name: "iPhone 11",
    brand: "Apple",
    price: 499,
    originalPrice: 699,
    rating: 4.4,
    reviews: 187,
    image: "/images/phone/iphone11.jpg",
    gallery_images: [
      "/images/phone/iphone11.jpg",
      "/images/phone/iphone111.jpg",
      "/images/phone/iphone112.jpg",
      "/images/phone/iphone113.jpg",
    ],
    condition: "Good",
    storage: "64GB",
    color: "Purple",
    category: "iPhone",
    availability: "in-stock",
    description:
      "iPhone 11 features dual-camera system with Night mode, all-day battery life, and the powerful A13 Bionic chip.",
    specifications: {
      display: {
        size: "6.1 inches",
        type: "Liquid Retina HD LCD",
        resolution: "1792 x 828 pixels",
        features: ["True Tone", "Wide color", "625 nits"],
      },
      performance: {
        processor: "A13 Bionic chip",
        ram: "4GB",
        storage: "64GB",
        os: "iOS 13 (upgradable)",
      },
      camera: {
        rear: "Dual 12MP (Wide, Ultra Wide)",
        front: "12MP TrueDepth",
        features: ["Night mode", "Deep Fusion", "Smart HDR", "4K video"],
      },
      battery: {
        capacity: "3110 mAh",
        charging: "18W wired, Qi wireless",
        life: "Up to 17 hours video playback",
      },
      connectivity: {
        network: "4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.0",
        other: ["Lightning port", "Face ID", "IP68 water resistance"],
      },
      physical: {
        dimensions: "150.9 x 75.7 x 8.3 mm",
        weight: "194g",
        materials: "Aluminum frame, Glass",
        colors: ["Purple", "Black", "White", "Green", "Yellow", "Red"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 21,
    features: [
      "A13 Bionic chip",
      "Dual-camera system",
      "Night mode",
      "All-day battery",
      "Face ID",
      "IP68 rating",
    ],
  },
  {
    id: "21",
    name: "Galaxy Z Flip 4",
    brand: "Samsung",
    price: 999,
    originalPrice: 1099,
    rating: 4.5,
    reviews: 64,
    image: "/images/phone/zflip4.jpg",
    gallery_images: [
      "/images/phone/zflip4.jpg",
      "/images/phone/zflip41.jpg",
      "/images/phone/zflip42.jpg",
      "/images/phone/zflip43.jpg",
    ],
    condition: "Excellent",
    storage: "256GB",
    color: "Bora Purple",
    category: "Samsung",
    availability: "in-stock",
    description:
      "Galaxy Z Flip 4 is the stylish foldable with Flex Mode, improved durability, and flagship performance in a compact flip phone design.",
    specifications: {
      display: {
        main: "6.7 inches Dynamic AMOLED 2X",
        cover: "1.9 inches Super AMOLED",
        resolution: "Main: 2640 x 1080, Cover: 260 x 512",
        features: ["120Hz adaptive refresh", "UTG", "HDR10+"],
      },
      performance: {
        processor: "Snapdragon 8+ Gen 1",
        ram: "8GB",
        storage: "256GB",
        os: "Android 12 (One UI 4.1.1)",
      },
      camera: {
        rear: "Dual 12MP wide, 12MP ultrawide",
        front: "10MP",
        features: ["Flex Mode", "Nightography", "Director's View"],
      },
      battery: {
        capacity: "3700 mAh",
        charging: "25W wired, 15W wireless, 4.5W reverse wireless",
        life: "Up to 18 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6E",
        bluetooth: "Bluetooth 5.2",
        other: ["USB-C", "Side-mounted fingerprint", "Samsung Pay"],
      },
      physical: {
        dimensions:
          "Unfolded: 165.2 x 71.9 x 6.9 mm, Folded: 84.9 x 71.9 x 15.9-17.1 mm",
        weight: "187g",
        materials: "Armor Aluminum frame, Gorilla Glass Victus+",
        colors: ["Bora Purple", "Graphite", "Pink Gold", "Blue"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 6,
    features: [
      "Foldable AMOLED",
      "Flex Mode",
      "Compact design",
      "IPX8 water resistance",
      "5G ready",
      "Flagship performance",
    ],
  },
  {
    id: "22",
    name: "Pixel 4a",
    brand: "Pixel",
    price: 349,
    originalPrice: 399,
    rating: 4.3,
    reviews: 89,
    image: "/images/phone/pixel4a.jpg",
    gallery_images: [
      "/images/phone/pixel4a.jpg",
      "/images/phone/pixel4a1.jpg",
      "/images/phone/pixel4a2.jpg",
      "/images/phone/pixel4a3.jpg",
    ],
    condition: "Good",
    storage: "128GB",
    color: "Just Black",
    category: "Pixel",
    availability: "in-stock",
    description:
      "Pixel 4a delivers Google's signature camera quality and pure Android experience in a compact, affordable package.",
    specifications: {
      display: {
        size: "5.81 inches",
        type: "OLED",
        resolution: "2340 x 1080 pixels",
        features: ["HDR", "Always-on display"],
      },
      performance: {
        processor: "Snapdragon 730G",
        ram: "6GB",
        storage: "128GB",
        os: "Android 10 (upgradable)",
      },
      camera: {
        rear: "Single 12.2MP",
        front: "8MP",
        features: ["Night Sight", "Portrait Mode", "Top Shot", "HDR+"],
      },
      battery: {
        capacity: "3140 mAh",
        charging: "18W wired",
        life: "Up to 24 hours battery life",
      },
      connectivity: {
        network: "4G LTE",
        wifi: "Wi-Fi 5",
        bluetooth: "Bluetooth 5.1",
        other: ["USB-C", "Rear fingerprint", "3.5mm headphone jack"],
      },
      physical: {
        dimensions: "144 x 69.4 x 8.2 mm",
        weight: "143g",
        materials: "Polycarbonate unibody",
        colors: ["Just Black"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 19,
    features: [
      "Great camera quality",
      "Compact design",
      "Pure Android",
      "Headphone jack",
      "Affordable price",
      "All-day battery",
    ],
  },
  {
    id: "23",
    name: "OnePlus 8T",
    brand: "OnePlus",
    price: 499,
    originalPrice: 599,
    rating: 4.4,
    reviews: 76,
    image: "/images/phone/8t.jpg",
    gallery_images: [
      "/images/phone/8t.jpg",
      "/images/phone/8t1.jpg",
      "/images/phone/8t2.jpg",
      "/images/phone/8t3.jpg",
    ],
    condition: "Very Good",
    storage: "128GB",
    color: "Aquamarine Green",
    category: "OnePlus",
    availability: "in-stock",
    description:
      "OnePlus 8T features 120Hz Fluid AMOLED display, Warp Charge 65, and flagship Snapdragon 865 performance.",
    specifications: {
      display: {
        size: "6.55 inches",
        type: "Fluid AMOLED",
        resolution: "2400 x 1080 pixels",
        features: ["120Hz refresh", "HDR10+", "1100 nits peak"],
      },
      performance: {
        processor: "Snapdragon 865",
        ram: "8GB",
        storage: "128GB",
        os: "Android 11 (OxygenOS 11)",
      },
      camera: {
        rear: "Quad 48MP main, 16MP ultrawide, 5MP macro, 2MP mono",
        front: "16MP",
        features: ["Nightscape", "UltraShot HDR", "Portrait Mode"],
      },
      battery: {
        capacity: "4500 mAh",
        charging: "65W Warp Charge",
        life: "Up to 27 hours video playback",
      },
      connectivity: {
        network: "5G, 4G LTE",
        wifi: "Wi-Fi 6",
        bluetooth: "Bluetooth 5.1",
        other: ["USB-C", "In-display fingerprint", "Alert Slider"],
      },
      physical: {
        dimensions: "160.7 x 74.1 x 8.4 mm",
        weight: "188g",
        materials: "Glass back, Aluminum frame",
        colors: ["Aquamarine Green", "Lunar Silver"],
      },
    },
    warranty: "12 months",
    inStock: true,
    stockCount: 13,
    features: [
      "120Hz AMOLED",
      "65W charging",
      "Flagship performance",
      "OxygenOS",
      "Alert Slider",
      "5G ready",
    ],
  },
];
